version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "customercheckout"
s3_bucket = "aws-sam-cli-managed-default-samclisourcebucket-1p8npvj70qz4v"
s3_prefix = "customercheckout"
region = "us-east-1"
capabilities = "CAPABILITY_IAM"
image_repositories = []
